export const ACTIVE_FORM_CHANGED = 'ACTIVE_FORM_CHANGED';
export const COMPONENT_TOGGLED = 'COMPONENT_TOGGLED';
export const FIELD_CHANGED = 'FIELD_CHANGED';
export const CONNECTION_FAILED = 'CONNECTION_FAILED';
export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS';
export const WEBSOCKET_MESSAGE = 'WEBSOCKET_MESSAGE';
export const IS_APP_STARTED = 'IS_APP_STARTED';