export const SET_YEAR = 'SET_YEAR';
export const FORM_CHANGED = 'FORM_CHANGED';
export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const ACTIVE_FORM_CHANGED = 'ACTIVE_FORM_CHANGED';
export const COMPONENT_TOGGLED = 'COMPONENT_TOGGLED';
export const FIELD_CHANGED = 'FIELD_CHANGED';